try{
    throw new Error('error');
}catch{
    console.log("An error");
}